### PR TITLE
Rename NestMC references, names etc. to Arbor.

### PR DESCRIPTION
**Pull request by halfflat**
* Use ARB_ and arb_ as variable prefixes in place of NMC_ and nmc_.
* Replace references to 'NestMC' and 'NEST MC' to refer instead to Arbor.
* Use 'arbor' as the sim name in generated validation data.
* Reflow long-line paragraphs in `tests/ubench/README.md`.
* Change names of CUDA mechanism and CUDA kernel libraries to include arbor name.

### CODE REVIEW

**Comment by halfflat** [comment]
Confirmed CUDA build builds.

**Comment by bcumming** [comment]
You missed a few:

https://github.com/halfflat/arbor/blob/feature/general-arbification/scripts/travis/build.sh#L47
https://github.com/halfflat/arbor/blob/feature/general-arbification/.ycm_extra_conf.py#L39
https://github.com/halfflat/arbor/blob/feature/general-arbification/.ycm_extra_conf.py#L57

**Comment by halfflat** [comment]
Updated with required edits.

**Comment by halfflat** [comment]
Confirmed successful build on KNL with `-DARB_VECTORIZE_TARGET=AVX2`

**Comment by bcumming** [comment]
And on KNL with AVX512?

**Comment by vkarak** [comment]
> And on KNL with AVX512?

This won't work with GCC yet, but yeah, we need  a system to test it...

**Pull request merged**
